from os import environ

API_URL = environ["API_URL"]
FRONT_URL = environ["FRONT_URL"]

OPENSEARCH_HOST = environ["OPENSEARCH_HOST"]
OPENSEARCH_PORT = environ["OPENSEARCH_PORT"]
OPENSEARCH_LOGIN = environ["OPENSEARCH_LOGIN"]
OPENSEARCH_PASSWORD = environ["OPENSEARCH_PASSWORD"]