from os import environ

VITE_API_URL = environ["VITE_API_URL"]
VITE_FRONT_URL = environ["VITE_FRONT_URL"]

OPENSEARCH_HOST = environ["OPENSEARCH_HOST"]
OPENSEARCH_PORT = environ["OPENSEARCH_PORT"]
OPENSEARCH_LOGIN = environ["OPENSEARCH_LOGIN"]
OPENSEARCH_PASSWORD = environ["OPENSEARCH_PASSWORD"]